// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpHim17IFdYUkd5jg4GEuPt05zl6i4m2Q',
    appId: '1:20540767204:web:2d2c920054df19e56c65f1',
    messagingSenderId: '20540767204',
    projectId: 'rbmice-472bb',
    authDomain: 'rbmice-472bb.firebaseapp.com',
    databaseURL: 'https://rbmice-472bb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rbmice-472bb.firebasestorage.app',
    measurementId: 'G-3NEKL0NGNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG8jKq3dWEYWBaiN7RahoK06qSDn7wpTM',
    appId: '1:20540767204:android:25eaf9c7ec7793be6c65f1',
    messagingSenderId: '20540767204',
    projectId: 'rbmice-472bb',
    databaseURL: 'https://rbmice-472bb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rbmice-472bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeJ_2s1LmOr_QhdulYgBm4gPQM17vwbMw',
    appId: '1:20540767204:ios:8aed12ee1a1abcda6c65f1',
    messagingSenderId: '20540767204',
    projectId: 'rbmice-472bb',
    databaseURL: 'https://rbmice-472bb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rbmice-472bb.firebasestorage.app',
    iosBundleId: 'com.example.rbm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeJ_2s1LmOr_QhdulYgBm4gPQM17vwbMw',
    appId: '1:20540767204:ios:8aed12ee1a1abcda6c65f1',
    messagingSenderId: '20540767204',
    projectId: 'rbmice-472bb',
    databaseURL: 'https://rbmice-472bb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rbmice-472bb.firebasestorage.app',
    iosBundleId: 'com.example.rbm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpHim17IFdYUkd5jg4GEuPt05zl6i4m2Q',
    appId: '1:20540767204:web:f1941677d774fdc86c65f1',
    messagingSenderId: '20540767204',
    projectId: 'rbmice-472bb',
    authDomain: 'rbmice-472bb.firebaseapp.com',
    databaseURL: 'https://rbmice-472bb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rbmice-472bb.firebasestorage.app',
    measurementId: 'G-EHFTPPDGFH',
  );

}